/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.spotless)
    alias(libs.plugins.versions)
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.slf4j.api)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.jupiter.params)
    testRuntimeOnly(libs.slf4j.simple)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    test {
        resources {
            srcDir(rootProject.layout.projectDirectory.dir("src/main/resources"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()

    // Stable defaults for IMDb-scale integration tests:
    // - single fork avoids concurrent large in-memory datasets
    // - periodic fork limits long-lived heap growth
    maxParallelForks = 1
    forkEvery = 12
    minHeapSize = "1g"
    maxHeapSize = "16g"
}

spotless {
    kotlin {
        target("src/**/*.kt")
        ktlint()
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}
