/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.spotless)
    alias(libs.plugins.versions)
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.slf4j.api)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.clikt)
    implementation(libs.sqlite.jdbc)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.jupiter.params)
    testRuntimeOnly(libs.slf4j.simple)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    sourceSets {
        named("main") {
            kotlin.srcDirs("src/main/kotlin")
        }
        named("test") {
            kotlin.srcDirs("src/test/kotlin")
        }
    }
}

tasks.register<JavaExec>("generateDatasetManifest") {
    group = "application"
    description = "Generate dataset-manifest.json for IMDb TSV/GZ files."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.kimdb.tsv.GenerateDatasetManifestKt"
    workingDir = rootProject.projectDir
}

tasks.register<JavaExec>("importImdbToSqlite") {
    group = "application"
    description = "Import IMDb TSV data into SQLite database."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.kimdb.tsv.ImportImdbToSqliteKt"
    workingDir = rootProject.projectDir
}

tasks.register<JavaExec>("benchmarkBackends") {
    group = "application"
    description = "Benchmark in-memory vs SQLite repository operations."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.kimdb.bench.BenchmarkBackendsKt"
    workingDir = rootProject.projectDir
}

sourceSets {
    main {
        java.srcDirs("src/main/kotlin")
        resources.srcDirs("src/main/resources")
    }

    test {
        java.srcDirs("src/test/kotlin")
        resources.srcDirs("src/test/resources")
        resources {
            srcDir(rootProject.layout.projectDirectory.dir("src/main/resources"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()

    // Stable defaults for IMDb-scale integration tests:
    // - single fork avoids concurrent large in-memory datasets
    // - periodic fork limits long-lived heap growth
    maxParallelForks = 1
    forkEvery = 12
    minHeapSize = "1g"
    maxHeapSize = "16g"
}

spotless {
    kotlin {
        target("src/**/*.kt")
        ktlint().editorConfigOverride(
            mapOf(
                "ij_kotlin_allow_trailing_comma" to "false",
                "ij_kotlin_allow_trailing_comma_on_call_site" to "false"
            )
        )
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint().editorConfigOverride(
            mapOf(
                "ij_kotlin_allow_trailing_comma" to "false",
                "ij_kotlin_allow_trailing_comma_on_call_site" to "false"
            )
        )
    }
}
